### PR TITLE
Timeline functionality

### PR DESCRIPTION
**Pull request by justincampbell**

### CODE REVIEW

**Comment by seejohnrun** [comment]
Nice - what do you think about storing the since_id in ~/.twitter alongside the keys and having timeline only retrieve new tweets?

**Comment by justincampbell** [comment]
Interesting. Should it return nothing or "No new tweets" if empty?

**Comment by justincampbell** [comment]
Returns nothing was the way to go in my opinion

**Comment by seejohnrun** [comment]
Yeah I'd go with return nothing

**Comment by seejohnrun** [comment]
Thanks so much for this contribution

**Pull request closed without merging**
